# fly.toml app configuration file generated for wordzoo-web-apex-wrapper on 2023-06-11T12:38:58-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wordzoo-web-apex-wrapper"
primary_region = "sjc"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
